### PR TITLE
Run DRB tests in parallel

### PR DESCRIPTION
**Pull request by BradSwain**
Right now it takes a long time to run the dataracebench test case because it is actually running ~100 sub tests sequentially.

I added a macro for defining the test cases so that each dataracebench test can be run in parallel.
I don't really like using macros, but I don't know of another way to create catch `TEST_CASE`s for each test, since `TEST_CASE` itself is a macro.

The new macro to register dataracebench tests looks like:

```cpp
TEST_LL("DRB001", "DRB001-antidep1-orig-yes.ll",
        EXPECTED("DRB001-antidep1-orig-yes.c:58:10 DRB001-antidep1-orig-yes.c:58:12"));
TEST_LL("DRB011", "DRB011-minusminus-orig-yes.ll",
        EXPECTED("DRB011-minusminus-orig-yes.c:74:16 DRB011-minusminus-orig-yes.c:74:16",
                 "DRB011-minusminus-orig-yes.c:74:16 DRB011-minusminus-orig-yes.c:74:16"));
TEST_LL("DRB041", "DRB041-3mm-parallel-no.ll", NORACE);
```

This shows a "yes" and a "no" case as an example.

The arguments to the `TEST_LL` macro are:
 1) test name
 2) filename
 3) Expected races

The test name is what is printed when running the test. For example, when running the tests with ctest, the output will look something like:

```shell
   Start 26: DRB001
1/9 Test #26: DRB001 ...........................   Passed    0.25 sec
    Start 27: DRB002
2/9 Test #27: DRB002 ...........................   Passed    0.24 sec
```

The file name is which file the tool should be run on.

The expected races can just be a list of the races expected.
The `EXPECTED` and `NORACE` macros don't actually do anything. I added them becaue I think it makes the macros easier to read.

If we decide this new syntax is ok, we can finish filling in all the other test cases, and maybe expand it to be used in other parts of the test code as well.

### CODE REVIEW

**Review by funemy — COMMENTED** [review]
I like the new changes here. Much better than construct a giant `Oracle`.
The `EXPECTED` macro, though tricky, makes the code much more readable.
So I would like to switch to this implementation.

**Comment by BradSwain** [comment]
I just pushed another change that updates how messages are printed when there is a failed test.

Now if a test fails the output should look something like this:

```shell
-------------------------------------------------------------------------------
DRB001
-------------------------------------------------------------------------------
../tests/integration/dataracebench.test.cpp:23
...............................................................................

../tests/helpers/ReportChecking.cpp:163: FAILED:
  REQUIRE( (missing.empty() && unexpected.empty()) )
with expansion:
  false
with message:
  1 Missed Races
        DRB001-antidep1-orig-yes.c:58:10 DRB001-antidep1-orig-yes.c:58:12
  1 Unexpected races
        DRB001-antidep1-orig-yes.c:58:10 DRB001-antidep1-orig-yes.c:58:10
```

**Comment by BradSwain** [comment]
Pushed another change that adds a flag for printing the trace to stdout.
It is on by default, but disabled during during drb tests.

This speeds up the tests a little more.

**Comment by BradSwain** [comment]
@funemy see my later comments.

If all the changes look good feel free to merge.

**Comment by funemy** [comment]
> @funemy see my later comments.
> 
> If all the changes look good feel free to merge.

I'm happy to merge this PR, but should I merge this branch with develop first, and change all test cases to this new syntax, then merge?

**Comment by BradSwain** [comment]
Good timing! I was updating the cases from develop as you posted your comment.

**Review by funemy — APPROVED** [review]

**Pull request merged**
