### PR TITLE
Refactor: lift IR to llvm Value for block metadata; add BlockIR

### PR DESCRIPTION
**Pull request by addison-coderrect**
Changes IR's getInst to getLLVMRepr and changes the return value from Instruction to Value to enable the creation of pseudo-IR to insert metadata as IR instructions.

Also introduces a new virtual IR, BlockIR, which demonstrates the need for the above change. This BlockIR is used to denote the beginning and ends of basic blocks which hold metadata, such as those necessary for #114.

### CODE REVIEW

**Comment by BradSwain** [comment]
So far the code itself looks good, but I would like to get a better idea of why `BlockIR` is needed.

Previously each IR type directly wraps an LLVM IR instruction, and then each event in the trace directly corresponds to an LLVM IR instruction. If an event needs some extra data about the LLVM module it can still access the underlying LLVM instruction.

I don't quite have a full picture of how `BlockIR` fits into this system yet. 

Can you include a little more about how this helps to model OpenMP sections?

**Comment by addison-coderrect** [comment]
I can add an implementation for sections with this, if you'd like, but long story short the idea is that sections are not instructions (unless we want to start tracking branches). Sections are implemented in LLIR as basic blocks.

e.g. https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB023-sections1-orig-yes.ll#L97

We don't care about the actual instructions here, but we do care about the metadata of the label and the block itself to identify that this is a section.

To implement sections, we identify the CallIR for `parallel sections`:
 - https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB023-sections1-orig-yes.c#L55

Then the BlockIR for each section:
 - https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB023-sections1-orig-yes.c#L57
 - https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB023-sections1-orig-yes.c#L59

**Comment by funemy** [comment]
So based on my quick reading, what you did to derive another subcalss called `BlockIR`, different from our previous `IR` (now renamed to `InstIR`).

`BlockIR` basically wraps a basic block, so you can access basic block names, such as `.omp.sections.case:`, which helps us to identify openmp section related code.

Am I correct? @addison-coderrect

**Comment by BradSwain** [comment]
I think I am getting a better idea.

So code like 

```cpp
#pragma omp parallel sections
{
  #pragma omp section
  { dostuff(); }
  #pragma omp section
  { launch(); }
}
```

would generate a trace like this?

```
BlockIR (some metadata)
Call dostuff
BlockIR (some metadata)
Call launch
```

**Comment by funemy** [comment]
First of all, I'm not against this design. But there are a few questions I would like to raise:

1. Basic block (BB) and Inst should not be in the same level. This PR mixed some BB with Inst (like Brad's example). If we seriously want to include the concept of BB in our IR, then BB should be a container of InstIR.
2. This brings some indirection, a BB cannot be view as a single IR, if there are multiple memory accesses in the BB, we still need to go inside the BB and traverse each instruction.
3. It seems what you want is the labels of BBs. You can still get those information from a instruction (`inst->getParent()` will return you the BB this instruction is in). It seems having this BlockIR doesn't provide much.

**Comment by addison-coderrect** [comment]
Ah, so just point the instructions for BlockStart and BlockEnd to the instructions at the beginning and end, extract the parent. The issue then becomes writing a recogniser for the start and end (I'd have to do inst->getParent().getInstList().front() == inst for start and rfront() for the end for every instruction...).

**Comment by addison-coderrect** [comment]
Long story short, if we want this kind of indirection, we would need a different model, which would in turn invalidate existing analyses... :upside_down_face: 

I see that CallIR is implemented similarly (flattening of instructions and denoting cal starts and ends); what distinguishes that from BlockIR (semantically or philosophically) beyond the use of a call instruction?

**Comment by funemy** [comment]
> 
> 
> Long story short, what you're saying is that if we want this kind of indirection, we would need a different model, which would in turn invalidate existing analyses... 🙃
> 
> I see that CallIR is implemented similarly (flattening of instructions and denoting cal starts and ends); what distinguishes that from BlockIR (semantically or philosophically) beyond the use of a call instruction?

1. `CallIR` directly corresponds to a `call` inst in LLVM bitcode (e.g. `call void (%struct.ident_t*, i32, void (i32*, i32*, ...)*, ...) @__kmpc_fork_call`). While `BlockIR` correspond to a basic block in llvm bitcode, which contains a list of instructions. That to me is already a big distinction. From the design of IR, basic block is used to denote the control flow, and it's at a different level with instructions.
2. I have no problem with adding BlockStart/BlockEnd to our traces and I can see it helps to identify omp sections. But to do that, is `BlockIR` needed, what benefit does `BlockIR` brings?

**Comment by addison-coderrect** [comment]
> > Long story short, what you're saying is that if we want this kind of indirection, we would need a different model, which would in turn invalidate existing analyses... upside_down_face
> > I see that CallIR is implemented similarly (flattening of instructions and denoting cal starts and ends); what distinguishes that from BlockIR (semantically or philosophically) beyond the use of a call instruction?
> 
>     1. `CallIR` directly corresponds to a `call` inst in LLVM bitcode (e.g. `call void (%struct.ident_t*, i32, void (i32*, i32*, ...)*, ...) @__kmpc_fork_call`). While `BlockIR` correspond to a basic block in llvm bitcode, which contains a list of instructions. That to me is already a big distinction. From the design of IR, basic block is used to denote the control flow, and it's at a different level with instructions.
> 
>     2. I have no problem with adding BlockStart/BlockEnd to our traces and I can see it helps to identify omp sections. But to do that, is `BlockIR` needed, what benefit does `BlockIR` brings?

1. Fair. I have no quarrel there.
2. BlockIR is like InstIR -- I would use that to make BlockStartIR and BlockEndIR, then extend from there to make specific kinds of blocks.

**Comment by funemy** [comment]
Also, invalidating our current analysis is fine, if the IR change really brings good benefits.

I would like to keep this discussion because I think include BB in our IR might be potentially helpful.

**Comment by funemy** [comment]
>     2. BlockIR is like InstIR -- I would use that to make BlockStartIR and BlockEndIR, then extend from there to make specific kinds of blocks.

I think `BlockStartIR` and `BlockEndIR` is good. But they should be a "fake instruction" (i.e. just inherit it from `InstIR`).

**Comment by addison-coderrect** [comment]
The reason I've segmented out BlockIR from InstIR is that InstIR explicitly is backed by an LLVM instruction, so types which extend InstIR can fallback to the Instruction return value from getLLVMRepr. Perhaps we have BlockIR extend something like "PseudoIR" to make super extra explicit that it's not backed by an LLVM instruction?

**Comment by funemy** [comment]
Some followup thoughts. Maybe you should consider call it `SectionStartIR` and `SectionEndIR`?

Because based on your description, you want to identify OpenMP sections easier. While each section region could contain multiple Basic Blocks.

So why don't you just do an analysis (based on the metadata of BBs if you will) and insert `SectionStartIR/SectionEndIR` in our trace to detect sections?

What do you think? @BradSwain @addison-coderrect

**Comment by addison-coderrect** [comment]
Segmentation of InstIR as "explicitly backed by instruction" is important for analysis that needs specifically instructions, but with no higher granularity: https://github.com/coderrect-inc/OpenRace/blob/8fb6e8e61069beebedc84e8a38f8a7011438385b/src/Analysis/OpenMPAnalysis.h#L31

**Comment by addison-coderrect** [comment]
> Some followup thoughts. Maybe you should consider call it `SectionStartIR` and `SectionEndIR`?

This PR is just abstractly about block-based analysis, which I suspect will show up again in the future. I haven't added anything specific to OpenMP's sections in this PR.

**Comment by funemy** [comment]
> 
> 
> > Some followup thoughts. Maybe you should consider call it `SectionStartIR` and `SectionEndIR`?
> 
> This PR is just abstractly about block-based analysis, which I suspect will show up again in the future. I haven't added anything specific to OpenMP's sections in this PR.

I totally agree that block-based analysis will appear in the future.
In that case we should seriously consider bringing BB into our IR, and make BB a container of a list of instructions.

**Comment by addison-coderrect** [comment]
> In that case we should seriously consider bringing BB into our IR, and make BB a container of a list of instructions.

BB already is a container of instructions, but in LLVM form -- I am a little concerned that going further into the lifting process may simply result in us rewriting LLVM IR... :upside_down_face:

Is the intent to get to a point where our analysis is graph theoretic? If so, we may want to look into embedding our IR directly into LLVM metadata instead of trying to do so externally.

**Comment by addison-coderrect** [comment]
Following some more conversation with Brad separately, I'm gonna close this for now, but leave the branch -- I'll revisit this with a better "feel" for how IR needs to change for block level analysis.

**Pull request closed without merging**
